$MODEL FinalModel
# 
# template file: Template.tpl
# ESATAN-TMS 2018 sp1, run date 9:27 Mon 27 Mar 2023
# Model name: FinalModel        Analysis case: orbit_mode12
#
  $LOCALS
  # GENCODE LOCALS - DO NOT REMOVE 
#
  $NODES
  # GENCODE NODES - DO NOT REMOVE 
#
  $CONDUCTORS
  # GENCODE CONDUCTORS - DO NOT REMOVE 
#
  $CONSTANTS
  # GENCODE CONSTANTS - DO NOT REMOVE 
#
  $ARRAYS
  # GENCODE ARRAYS - DO NOT REMOVE 
#
  $EVENTS
  # GENCODE EVENTS - DO NOT REMOVE 
#
  $SUBROUTINES
  # GENCODE SUBROUTINES - DO NOT REMOVE 
C
  $INITIAL
  # GENCODE BOUNDARY_CONDS - DO NOT REMOVE 
  # GENCODE INITIAL - DO NOT REMOVE 
C
  $EXECUTION
C
C Steady State Solution
C
      RELXCA=0.01
      NLOOP=100
C
      CALL SOLVFM
C
C Transient Solution
C
      TIMEND=PERIOD
      DTIMEI=TIMEND/100.0
      OUTINT=TIMEND/10.0
C
      CALL SLCRNC

C
      TIMEND=5736.629733557936
      OUTINT=573.6629733557936
      NLOOP=100
      RELXCA=0.01
      DTIMEI=100.0
      CALL SLCRNC
C
C
      TIMEND=5736.629733557936
      OUTINT=573.6629733557936
      NLOOP=100
      RELXCA=0.01
      DTIMEI=100.0
      CALL SOLCYC('SLCRNC',0.01D0,0.01D0,5736.629733557936D0,10,' ','NONE')
C
      CALL SLCRNC
C
C
      NLOOP=100
      RELXCA=0.01
      CALL SOLVFM
C
C
      NLOOP=100
      RELXCA=0.01
      CALL SOLVFM
C
  $VARIABLES1
  # GENCODE VARIABLES1 - DO NOT REMOVE 
C
  $VARIABLES2
  # GENCODE VARIABLES2 - DO NOT REMOVE 
C
  $OUTPUTS
      CALL PRNDTB(' ', 'L, T, QS, QE, QA, QI, C', CURRENT)
C
      CALL DMPTMD(' ', 'NODES, CONDUCTORS', CURRENT, ' ')

  # GENCODE OUTPUTS - DO NOT REMOVE 
C
$ENDMODEL FinalModel
